### ISSUE TITLE
Supporting Google OAuth2

### ISSUE THREAD

**Issue by chrisabruce** [ctron/yew-oauth2#9]
What is the recommended way to support Google's OAuth2 implementation. Google requires `scope` and has many additional parameters.  As an example:
```
https://accounts.google.com/o/oauth2/v2/auth?
 scope=https%3A//www.googleapis.com/auth/drive.metadata.readonly&
 access_type=offline&
 include_granted_scopes=true&
 response_type=code&
 state=state_parameter_passthrough_value&
 redirect_uri=https%3A//oauth2.example.com/code&
 client_id=client_id
```

**Comment by ctron** [comment]
I think most of the parameters are standard OAuth2 parameters, which will be set automatically.

But you are right, some of them (like scope) and arbitrary custom parameter can currently not be set. I think it would make sense to amend this though. Would be you able to come up with a PR?

**Comment by ctron** [comment]
Actually you can set scopes, I was looking in the wrong location :facepalm: … 

https://github.com/ctron/yew-oauth2/blob/49d35734a8ac153e360e9c17c79778b06ad51ea6/src/components/context.rs#L18

For the other parameters, it might make sense to either amend the `Config` structure. Or, if they are more generic, add them to the component properties too.

**Comment by chrisabruce** [comment]
Yeah I use the scopes prop to pass. I will create a PR for rest. Maybe good approach would be to add any common oauth ones to `config` and maybe the rest as a new property called `params` or something?

**Comment by mh84** [comment]
I'm encountered a similar problem when working with Discords OAuth2, where there is a query option `prompt=none` which requires the user to allow app permission only once. This works fine for login purposes as we can just use `start_login_opts(...)`, but this doesnt work when there is an redirect because of unauthenticated state.

I was able to cover this problem locally by introducing LoginOptions as property of the OAuth2 struct like this:
`    let mut hashmap = HashMap::new();
    hashmap.insert("prompt".to_string(), "none".to_string());
    let options = LoginOptions { query: hashmap };

    html!(
        <>
        <OAuth2 {config} {scopes} {options}>
...`

I can provide a PR with the changes made, if that way looks fine.

**Comment by ctron** [comment]
As PR #9 is merged and released, can we close this issue?
